Portfolio: finish mobile version
shm04/my-portfolio pull request #2
Opened 2023-01-19 19:10 UTC by shm04

# Finish mobile version

## In index.html and style.css I do:

- "Works" section
- About myself section

2023-01-19 21:51 UTC, NahnahAJ requested changes
Hi @shm04 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- Professional README :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 

## Required Changes ♻️
- Please Fix the GitHub deployment error
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Writing a more descriptive Pull Request. You can refer to this [link](https://hugooodias.medium.com/the-anatomy-of-a-perfect-pull-request-567382bb6067) to learn more about this.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 21:51 UTC, NahnahAJ commented on index.html
> +            <p class="p-text">Project name goes here</p>
- [ ] I noticed here that your project name was put in a (`p` tag) but since it is not a paragraph but the name of the project, it makes it the title or header of that container. So I suggest you use one of the header tags ie. (`h2,h3,h4 etc`) instead of the (`p` tag) :wink: 
- [ ] Kindly repeat this process for all the other project names :100:

2023-01-19 21:51 UTC, NahnahAJ commented on index.html
> +                <a class="see-btn" href="#">See this project<img class="arrow" src="imgs/arrow.png"></a>
- [ ] I noticed here that your buttons are missing the button interaction styles ie. Active, Hover, and Pressed. I would suggest that you include these in your project to enhance user interactivity :+1: and also so you can meet all the project requirements :+1: 
- [ ] Please refer to the Figma design and fix this according to the design guidelines. I have attached a screenshot below :100: 
- [ ] Please ensure that the right styles have been applied to each of the buttons in your project :wink: 
- Project requirement for button interaction styles
![image](https://user-images.githubusercontent.com/102699958/213559671-64092255-aa1b-41e7-a433-5cd779247efe.png)
- Figma Design for button interaction styles
![image](https://user-images.githubusercontent.com/102699958/213560153-80060efc-cdcd-4e26-b88c-285111cedfde.png)

2023-01-19 21:51 UTC, NahnahAJ commented on index.html
> +        <img class="p-img" src="imgs/img1.jpg">
- [ ] I noticed that your images for each work were outside of the `section` in your case but ideally, all the contents of a container should be in that container and styled accordingly. So kindly fix this as well.
- [ ] I also noticed that your images have not properly filled their container. If after putting them in the same container as the other work details this problem still persists, I suggest you use the `width:  -webkit-fill-available;` :100: Using this property on images can be beneficial if you want the images to fill the available space within the parent container. 
- [ ] Kindly fix all the other images in your project that are behaving like that. :+1: 
- [ ]  I have attached a video below to further explain what I mean.
[Screencast from 01-19-2023 09:21:22 PM.webm](https://user-images.githubusercontent.com/102699958/213565533-d5b6de33-158e-4d2b-bec1-ab5ce9b61be4.webm)

2023-01-20 01:55 UTC, wayungi requested changes
Hi @shm04 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there is still one which isn't addressed yet.


![image](https://user-images.githubusercontent.com/99656687/213601181-b6b8d0b3-14ae-4089-8cc6-b0644d7a02f0.png)

 ## Highlights
- [ ] Good PR title 😄 
- [ ] GitHub flow 😄 
- [ ] Descriptive commit message ✔️ 
- [ ] Professional README ✔️ 
- [ ] All linter checks passing ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 01:55 UTC, wayungi commented on index.html
> +            <p class="p-text">Project name goes here</p>
- [ ] As requested by @NahnahAJ , please change all ocurrances of `<p class="p-text">Project name goes here</p>`  to  `<h2 class="p-text">Project name goes here</h2>`. There are 5 occurrences that need to be changed. You will find one in each of your projects in the project section

2023-01-20 06:26 UTC, emmiiorji approved these changes
Hi @shm04, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/211860036-ec03abcf-8d2e-457c-948f-9afe812722fe.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow
- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 14:07 UTC, merged