Portfolio: add a contact form and finish the mobile version.
shm04/my-portfolio pull request #3
Opened 2023-01-24 18:25 UTC by shm04

### In this pull request we:

- Add contact form and footer in index.html
- Add contact form and footer style in style.css

2023-01-24 19:03 UTC, Gambit142 requested changes
Hi @shm04 @ghreza-crypto 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Descriptive pull request summary ✔️ 
- Good commit messages ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-25 17:33 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @shm04, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 17:33 UTC, brainconnect93 commented on index.html
> +        </form>
- [ ] Having made a great effort working on the changes requested by the previous reviewer, I noticed the form submission is still not working, anytime I tried to submit a message via the form it throws an error.
  - I would kindly suggest you make the `required` attribute come last in the `input` tag i.e it should come after the max length attribute.
  - Also give the input tag a `name attribute` with the value of `fullName`. I believe with these changes the error will be resolved and I would advise you to try and submit a message via the form from your end and be sure the form is submitted successfully before submitting it for another review.

Error message 👇 

![form1](https://user-images.githubusercontent.com/78634841/214638381-e6423f57-ec93-4e26-bf27-db9f414ed637.png)

2023-01-25 18:03 UTC, Tadesse-Alemayehu approved these changes
### Hi Team 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
 - [ ]  Good commit history. ✅
 - [ ]  Good PR title/description. ✅
 - [ ]  All linters passed ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 18:11 UTC, merged